version: "3.8"

services:
  postgres-staff-base:
    container_name: postgres-staff-base
    image: postgres:${POSTGRES_VERSION}
    restart: on-failure
    env_file:
      - .env
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./.docker-volumes/postgres:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/pre_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      staff-base-net:
        ipv4_address: 172.28.1.1

  liquibase-staff-base:
    container_name: liquibase-staff-base
    image: liquibase/liquibase:${LIQUIBASE_VERSION}
    restart: on-failure
    command: --defaultsFile=liquibase.properties update
    depends_on:
      - postgres-staff-base
    volumes:
      - ./migration/:/liquibase/changelog/
      - ./migration/:/liquibase/classpath/
      - ./migration/liquibase.properties:/liquibase/liquibase.properties
    networks:
      staff-base-net:
        ipv4_address: 172.28.1.2

networks:
  staff-base-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16