CREATE SCHEMA IF NOT EXISTS staff_base;

CREATE TABLE employee
(
    id        bigint generated by default as identity primary key,
    full_name varchar(255)        not null,
    phone     varchar(31) unique  not null,
    age       smallint            not null,
    email     varchar(255) unique not null,
    address   varchar(255)        not null
);

CREATE INDEX employee_full_name ON employee USING btree(full_name);